# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 102edfc91c791fdae50ed3e5c8fb103a6031e4a7cb46618f9ab669144a9d2a56e940d7ccf9682abc2de74a2e923ecc4f07fb41a2c52d49e8362efc5c46f0fb06

test:
  secret_key_base: 922ae9c67976d202d8e6396cbe26daee758f5e6897f9fa83fa2eb04ec676e9f0cda8052104c2e5c63fd20bee0d2c656b9d82bf13bdd13507e8f6ca1f96d9db2b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
